### ISSUE TITLE
colocar informações de contato suas

### ISSUE THREAD

**Issue by davidsonfellipe** [guipn/sinful.js#18]
Estava buscando uma forma de contato (twitter ou email) para te referenciar na Weekly e não achei... =)

**Comment by guipn** [comment]
Feito :)

https://github.com/guipn/sinful.js/wiki/Contact

**Comment by davidsonfellipe** [comment]
obrigado. vamo colocar na proxima weekly do braziljs!

**Comment by guipn** [comment]
Opa, legal! :)
