### ISSUE TITLE
Why the zipWith trims values?

### ISSUE THREAD

**Issue by ashnur** [guipn/sinful.js#21]
Hi,

I find it interesting, that it was implemented this way. I think using .longest() instead of .shortest() in zipWith would make much more sense.

**Comment by ghost** [comment]
Both have their uses. Keeping the "trimming" one but adding one that doesn't (perhaps as an optional parameter?) could be useful.

I believe Haskell's zipWith uses the shorter length because infinite lists are in the language and it would otherwise run forever if either argument was such a list. This is clearly not the case with JS.

**Comment by guipn** [comment]
The idea is that `zipWith` is defined over elements that exist, so argument functions never have to treat `undefined`.

If, however, you do happen to have a function to be passed as argument that treats `undefined` properly and would fit your use case nicely, you do have the option to push `undefined` to the arrays to be zipped:

```
function pushN(array, n, value) {
    while (n-- > 0) {
        array.push(value);
    }

    return array;
}

var a = [1, 2], 
     b = [4, 5], 
     c = [7, 8, 9, 10];

Array.zipWith(Math.max, pushN(a, 2, undefined), pushN(b, 2, undefined), c);
// returns [7, 8, NaN, NaN]
```

If `longest` were used, going the other way around would require copying:

```
// supposing zipWith uses longest

var a = [1, 2], 
     b = [4, 5], 
     c = [7, 8, 9, 10];

Array.zipWith(Math.max, a, b, c.slice(0, 2));
// would return [7, 8]
```

My own, questionable opinion is that the current implementation makes for less surprises. Not only do I think it makes sense to expect that elements must exist to be included in the zipped result, but current implementations of `zipWith` in other languages also follow that line of thought (see Python, Haskell). That alone is, in my opinion, a strong reason to follow suit.

**Comment by ashnur** [comment]
I often need to pair up values from arrays. So in my case I have 2 arrays, and want to keep all the values, and treat shorter arrays just as long as the longest one, with undefined values.

The  while loop to pad the shorter array with undefined is uglier and less clear than just using a for loop, and calling a function in that. That could be the most convenient and clear thing I can do, but I started to like iterator methods, so I asked people on irc and Raynos on freenode.#javascript pointed out to me the zipWith implementation from [zippy](https://github.com/jesusabdullah/node-zippy). 

I am using that now, but I found it interesting that sinful has the other way around, and I got curious what was the idea behind it, why like this. From what you say, I guess it's because of Haskell. 

(btw. you can close this issue if you want, thanks for the answers)

**Comment by guipn** [comment]
Danny makes a good point -- providing both would likely be the better option. I think a separate routine would be ideal, since current calls already involve many arguments. I may do this tonight.
