### ISSUE TITLE
jQuery Conflict

### ISSUE THREAD

**Issue by bigorangemachine** [guipn/sinful.js#22]
When I do an jquery (1.10.2) ajax call (without using sinful anywhere!) I get
'Uncaught TypeError: object is not a function sinful.js:112'

Simply:

```
var calculator_obj;//set for global context
$.ajax({
    'url':'data/calculator.json',
    'success':function(dataIn){
        calculator_obj=new calc_prototype($('body')[0],dataIn.defaults);
    },
    'type':'GET',
    'dataType':'json'
});
```

Seems to be part of 'x.extend.ajax' in jQuery.
And yes, I did use jQuery noConflict!
Any ideas?!

**Comment by guipn** [comment]
May I get a testcase?

Cheers

**Comment by bigorangemachine** [comment]
calculator.json

```
{"defaults":{"value1":100,"value2":20}}
```

```
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script type="text/javascript" src="js/sinful.js"></script>
<script type="text/javascript">
var calculator_obj;//set for global context
$.ajax({
    'url':'data/calculator.json',
    'success':function(dataIn){
alert('done!');
    },
    'type':'GET',
    'dataType':'json'
});
</script>
```

Test case?
Thats all it takes to replicate the error.

I resolved the error by reducing sinful to only use the parts I need.  However, considering the wide adoption of jQuery I'm sure this issue will come up for others

**Comment by guipn** [comment]
I've reduced the testcase to the following snippet:

```
<script src="jquery-1.10.2.js"></script>
<script type="text/javascript">
Object.prototype.foo = function () {
    alert("Now THAT's sinful!");
};

$.ajax({
    url: 'data/calculator.json',
    success: function () {},
    type: 'GET',
    dataType: 'json'
});
</script>
```

Notice sinful.js isn't included here. Assigning a function to a property of Object.prototype and then calling `$.ajax` implies on that function being called. This is not what I'd expect, and I don't think it's what the JQuery folks intended either. 

I've dug down to JQuery 1.10.2's `ajaxSetup` function, starting at line 7860, but stopped there. 

At this point, it's clear to me that it's more of an issue with JQuery than it is with sinful.js.

**Comment by ashnur** [comment]
Definitely not sinful.js issue. 
https://github.com/jquery/jquery/blob/0d68b7877f761264bfe4950e4df156b854925a6b/src/ajax.js#L616 
that's an unguarded `for..in` over a newly created object.

**Comment by guipn** [comment]
Thanks for the input, ashnur.

Take care.

**Comment by lincanbin** [comment]
I have reproduced this conflict in jQuery v1.11.2 with Intel appframework [af.popup.js](https://github.com/01org/appframework/blob/master/plugins/af.popup.js)

``` javascript
    $("#afui").popup({
        title: 'test',
        message: "test",
        cancelText: "cancel",
        cancelCallback: function(){},
        doneText: "Done",
        doneCallback: function(){
            $.ajax({
                url: '/reply',
                data:{
                    TopicID: 123
                },
                type: 'post',
                dataType: 'json',
            });
        },
        cancelOnly: false
    });
```

```
Uncaught TypeError: object is not a function jquery.js:4
m.extend.ajax jquery.js:4
Reply.$.popup.doneCallback mobile.global.js?version=3.2.95:117
(anonymous function) appframework.popup.js?version=3.2.95:126
m.event.dispatch jquery.js:3
r.handle jquery.js:3
```

**Comment by bigorangemachine** [comment]
@lincanbin You will have to adjust the sinful.js code to not extend Objects.  

The code features an extension of the native JavaScript object that will require you to adjust the popular jQuery framework or for your own version of sinful.  

While this method of Javascript coding has been frowned upon for some time it is how this framework works and you'll have to work around it.  My solution was to rewrite the sinful.js code into normal functions
