### ISSUE TITLE
Object.prototype extension conflict with jQuery

### ISSUE THREAD

**Issue by sphenk** [guipn/sinful.js#24]
Hi Guilherme,

I need to comment out all Object.prototype extensions when loading sinful.js after jQuery 1.10.2 (in Firefox 26).
Probably, this is just jQuery ignoring the case that some other framework may extend Object, but I just wanted to let you know.

Cheers,

Henk

**Comment by guipn** [comment]
Thanks for commenting. We've recently been informed about it (see https://github.com/guipn/sinful.js/issues/22#issuecomment-30401452).

Cheers.
